In [1]:
import os
import keras
import numpy as np
import warnings
warnings.filterwarnings("ignore")

Using TensorFlow backend.


In [2]:
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing.image import load_img, img_to_array

In [4]:
model=VGG16()

In [5]:
model.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [6]:
img=load_img('pizza.jpg',target_size=(224,224))

In [7]:
img.size

(224, 224)

In [8]:
img_array=img_to_array(img)

In [9]:
img_array.shape

(224, 224, 3)

In [11]:
img_array=np.expand_dims(img_array,axis=0)

In [12]:
img_array.shape

(1, 224, 224, 3)

In [13]:
img_array

array([[[[134.,  58.,  32.],
         [135.,  59.,  33.],
         [135.,  59.,  33.],
         ...,
         [ 53.,  30.,  16.],
         [ 59.,  36.,  22.],
         [ 65.,  42.,  28.]],

        [[135.,  59.,  33.],
         [135.,  59.,  33.],
         [135.,  59.,  33.],
         ...,
         [ 52.,  29.,  15.],
         [ 58.,  35.,  21.],
         [ 64.,  41.,  27.]],

        [[135.,  59.,  33.],
         [135.,  59.,  33.],
         [135.,  59.,  33.],
         ...,
         [ 51.,  28.,  14.],
         [ 57.,  34.,  20.],
         [ 63.,  40.,  26.]],

        ...,

        [[217., 190., 123.],
         [203., 175., 110.],
         [204., 176., 113.],
         ...,
         [156.,  87.,  54.],
         [154.,  85.,  52.],
         [156.,  87.,  54.]],

        [[244., 164.,  13.],
         [238., 160.,   2.],
         [238., 162.,   0.],
         ...,
         [133.,  79.,  35.],
         [133.,  79.,  35.],
         [133.,  79.,  35.]],

        [[244., 164.,  13.],
       

In [14]:
img_preprocessed = preprocess_input(img_array)

In [15]:
img_preprocessed

array([[[[ -71.939   ,  -58.779   ,   10.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         ...,
         [ -87.939   ,  -86.779   ,  -70.68    ],
         [ -81.939   ,  -80.779   ,  -64.68    ],
         [ -75.939   ,  -74.779   ,  -58.68    ]],

        [[ -70.939   ,  -57.779   ,   11.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         ...,
         [ -88.939   ,  -87.779   ,  -71.68    ],
         [ -82.939   ,  -81.779   ,  -65.68    ],
         [ -76.939   ,  -75.779   ,  -59.68    ]],

        [[ -70.939   ,  -57.779   ,   11.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         [ -70.939   ,  -57.779   ,   11.32    ],
         ...,
         [ -89.939   ,  -88.779   ,  -72.68    ],
         [ -83.939   ,  -82.779   ,  -66.68    ],
         [ -77.939   ,  -76.779   ,  -60.68    ]],

        ...,

        [[  19.060997,   73.221   ,   

In [16]:
from keras.applications.vgg16 import decode_predictions

In [17]:
preds=model.predict(img_preprocessed)

In [18]:
preds

array([[3.31308385e-08, 7.54643179e-06, 4.53889214e-07, 2.13575788e-07,
        4.57115505e-07, 2.46131663e-06, 1.97644994e-07, 6.12580516e-06,
        3.26375302e-05, 2.40102372e-06, 8.41848077e-07, 3.92570257e-07,
        8.05205764e-06, 4.87826810e-07, 1.51754278e-07, 1.21294693e-06,
        1.54036783e-07, 7.01735416e-07, 4.18905131e-07, 2.33511537e-06,
        2.71550448e-07, 2.37212998e-06, 6.98359941e-07, 1.28278509e-06,
        2.50169734e-07, 8.63948969e-07, 2.09252516e-06, 1.20825393e-06,
        1.06019752e-06, 9.16420731e-07, 1.74963361e-07, 1.25727752e-07,
        1.07493850e-06, 7.11832718e-06, 6.11525991e-07, 1.47403085e-07,
        7.48665968e-07, 6.08619303e-07, 5.47814807e-06, 2.86614579e-07,
        1.15049581e-07, 1.43109204e-07, 1.00273758e-06, 8.86884663e-07,
        1.35250474e-07, 8.83711891e-07, 3.32498544e-08, 6.03855369e-07,
        4.14871124e-08, 2.57326207e-07, 6.45499313e-07, 4.10507300e-06,
        2.86778089e-07, 2.36137581e-07, 1.75719524e-05, 3.518958

In [20]:
decode_predictions(preds,top=10)

40960/35363 [==================================] - 0s 2us/step


[[('n07873807', 'pizza', 0.8147561),
  ('n01981276', 'king_crab', 0.046815865),
  ('n04270147', 'spatula', 0.017587706),
  ('n07875152', 'potpie', 0.01612254),
  ('n07831146', 'carbonara', 0.014762542),
  ('n07711569', 'mashed_potato', 0.009485477),
  ('n07579787', 'plate', 0.008995411),
  ('n07684084', 'French_loaf', 0.008081657),
  ('n02776631', 'bakery', 0.0068916366),
  ('n03400231', 'frying_pan', 0.0045392676)]]